### ISSUE TITLE
Warning: Prop `className` did not match. Server, Client

### ISSUE THREAD

**Issue by vipinlahoti** [ErikDakoda/vulcan-material-ui#6]
When ever I use chips for categories list or a card I gets a following error message as:
Warning: Prop `className` did not match. Server: "MuiChip-label-131" Client: "MuiChip-label-130"

**Comment by ErikDakoda** [comment]
Hi! Sorry for the late reply. 

That's related to server side rendering (SSR). Sometimes the React rendered on the server and the client don't match exactly and this causes a problem with JSS. Anyway, it's something complicated that I have struggled with. I am working on solving each of the issues causing this over time.

In the meantime, in your own code, make sure that your components will render the same on the server and the client. This means not referring to client-side object such as `document` or `jQuery`.

Actually I will add this to the ReadMe because I am sure other people will encounter this issue.
